spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rchome
    username: gabone
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true